'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5477
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace My.Resources


	''' <summary>
	'''   A strongly-typed resource class, for looking up localized strings, etc.
	''' </summary>
	' This class was auto-generated by the StronglyTypedResourceBuilder
	' class via a tool like ResGen or Visual Studio.
	' To add or remove a member, edit your .ResX file then rerun ResGen
	' with the /str option, or rebuild your VS project.
	<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(), _
	Global.Microsoft.VisualBasic.HideModuleNameAttribute()> _
	Friend Module Resources

		Private resourceMan As Global.System.Resources.ResourceManager

		Private resourceCulture As Global.System.Globalization.CultureInfo

'		internal Resources()
'		{
'		}

		''' <summary>
		'''   Returns the cached ResourceManager instance used by this class.
		''' </summary>
		<Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
		Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
			Get
				If Object.ReferenceEquals(resourceMan, Nothing) Then
					Dim temp As New Global.System.Resources.ResourceManager("Resources", GetType(Resources).Assembly)
					resourceMan = temp
				End If
				Return resourceMan
			End Get
		End Property

		''' <summary>
		'''   Overrides the current thread's CurrentUICulture property for all
		'''   resource lookups using this strongly typed resource class.
		''' </summary>
		<Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
		Friend Property Culture() As Global.System.Globalization.CultureInfo
			Get
				Return resourceCulture
			End Get
			Set(ByVal value As System.Globalization.CultureInfo)
				resourceCulture = value
			End Set
		End Property

		Friend ReadOnly Property AddUserIcon() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("AddUserIcon", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property BackIcon() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("BackIcon", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property BoldIcon() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("BoldIcon", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property BullletIcon() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("BullletIcon", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property BullletNumberIcon() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("BullletNumberIcon", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property CameraIcon() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("CameraIcon", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property CheckMarkIcon() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("CheckMarkIcon", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property DateIcon() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("DateIcon", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property DocIcon() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("DocIcon", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property HelpIcon() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("HelpIcon", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property IndentIcon() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("IndentIcon", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property ItalicIcon() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("ItalicIcon", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property LinkIcon() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("LinkIcon", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property OutdentIcon() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("OutdentIcon", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property PageColorIcon() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("PageColorIcon", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property PageWidthIcon() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("PageWidthIcon", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property PicturesIcon() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("PicturesIcon", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property RedoIcon() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RedoIcon", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property SearchIcon() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("SearchIcon", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property StarIcon() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("StarIcon", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property StrikeIcon() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("StrikeIcon", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property SyncIcon() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("SyncIcon", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property TableIcon() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("TableIcon", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property TagIcon() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("TagIcon", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property TextColorIcon() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("TextColorIcon", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property TextHighlightIcon() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("TextHighlightIcon", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property TextStylesIcon() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("TextStylesIcon", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property UnderlineIcon() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("UnderlineIcon", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property UndoIcon() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("UndoIcon", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property
	End Module
End Namespace
